// This file is generated by Slice Machine. Update with care!

import ContactBlock from './ContactBlock';
import ContactForm from './ContactForm';
import Image from './Image';
import Quote from './Quote';
import Text from './Text';

export {
	ContactBlock,
	ContactForm,
	Image,
	Quote,
	Text,
};

export const components = {
	contact_block: ContactBlock,
	contact_form: ContactForm,
	image: Image,
	quote: Quote,
	text: Text,
};
